FUNCTION appl_log_display.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(OBJECT) TYPE  BALOBJ_D OPTIONAL
*"     REFERENCE(SUBOBJECT) TYPE  BALSUBOBJ OPTIONAL
*"     REFERENCE(EXTERNAL_NUMBER) TYPE  BALNREXT OPTIONAL
*"     REFERENCE(OBJECT_ATTRIBUTE) TYPE  I OPTIONAL
*"     REFERENCE(SUBOBJECT_ATTRIBUTE) TYPE  I OPTIONAL
*"     REFERENCE(EXTERNAL_NUMBER_ATTRIBUTE) TYPE  I OPTIONAL
*"     REFERENCE(DATE_FROM) TYPE  D OPTIONAL
*"     REFERENCE(TIME_FROM) TYPE  T OPTIONAL
*"     REFERENCE(DATE_TO) TYPE  D OPTIONAL
*"     REFERENCE(TIME_TO) TYPE  T OPTIONAL
*"     REFERENCE(TITLE_SELECTION_SCREEN) OPTIONAL
*"     REFERENCE(TITLE_LIST_SCREEN) OPTIONAL
*"     REFERENCE(COLUMN_SELECTION) TYPE  BALDISP OPTIONAL
*"     REFERENCE(SUPPRESS_SELECTION_DIALOG) TYPE  CHAR1 OPTIONAL
*"     REFERENCE(COLUMN_SELECTION_MSG_JUMP) TYPE  CHAR1 OPTIONAL
*"     REFERENCE(EXTERNAL_NUMBER_DISPLAY_LENGTH) TYPE  I OPTIONAL
*"     REFERENCE(I_S_DISPLAY_PROFILE) TYPE  BAL_S_PROF OPTIONAL
*"     REFERENCE(I_VARIANT_REPORT) TYPE  SYREPID OPTIONAL
*"     REFERENCE(I_SRT_BY_TIMSTMP) TYPE  BOOLEAN OPTIONAL
*"  EXPORTING
*"     REFERENCE(NUMBER_OF_PROTOCOLS) TYPE  I
*"  EXCEPTIONS
*"      NO_AUTHORITY
*"----------------------------------------------------------------------

  ASSERT 1 = 'todo'.

ENDFUNCTION.